<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{class}\' must extend from \'yii\\rbac\\Rule\' or its child class' => '\'{class}\' 必须继承自 \'yii\\rbac\\Rule\' 或者是其子类',
    'Action' => '操作',
    'Are you sure to delete this item?' => '确定要删除这一项?',
    'Assign' => '分配',
    'Assignment : {0}' => '分配权限 : {0}',
    'Assignments' => '分配权限',
    'Class Name' => '类名',
    'Create' => '创建',
    'Create Rule' => '创建规则',
    'Create Role' => '创建角色',
    'Data' => '内容',
    'Delete' => '删除',
    'Description' => '描述',
    'Invalid rule "{value}"' => '错误的规则: "{value}"',
    'Item has been removed.' => '项目已经移除',
    'Item has been saved.' => '项目已经保存',
    'Name' => '名字',
    'Permissions' => '权限',
    'Refresh' => '刷新',
    'Remove' => '移除',
    'Roles' => '角色',
    'Role : {0}' => '角色 : {0}',
    'Permission : {0}' => '权限 : {0}',
    'Create Permission' => '创建权限',
    'Routes' => '路由',
    'Rule' => '规则',
    'Rule "{value}" does not exists' => '规则 "{value}" 不存在',
    'Rule : {0}' => '规则 : {0}',
    'Rule Name' => '规则名称',
    'Rule has been deleted.' => '规则已经删除',
    'Rule has been saved.' => '规则已经保存',
    'Rules' => '规则',
    'Search for assigned' => '搜索被分配的',
    'Search for available' => '搜索可以获取的',
    'The requested page does not exist.' => '请求的页面不存在!',
    'Type' => '类型',
    'Unknown class \'{class}\'' => '未知类 \'{class}\'',
    'Update' => '更新',
    'Update Rule : {0}' => '更新规则 : {0}',
    'Update Role : {0}' => '更新角色 : {0}',
    'Update Permission : {0}' => '更新权限 : {0}',
    'Select Rule' => '选择规则',
    'Role has been deleted.' => '角色已经删除!',
    'Role cannot be deleted!' => '角色有关联的用户,不允许删除!',
    'Role has been saved.' => '角色已经保存!',
    'Cancel' => '取消',

];
